Feature/#3wmb7w8 device passcodes
ManageXR/mxr-unity-sdk pull request #22
Opened 2023-03-15 21:03 UTC by adrenak

2023-03-16 00:14 UTC, johnmanagexr requested changes
Code here looks good, but I'm missing the context on why this change is necessary. Can you add some information to the specific ticket for this task and why these changes are needed on the SDK side (besides HomeScreenTypes.cs - I can follow that one :) )

2023-03-20 19:38 UTC, adrenak commented
The cause for changes is that for the recent features we've been adding to custom launcher 
`AndroidAppMessengerManager.cs` has to be made public (it was previously internal, C# term for public within the DLL, in our case the SDK DLL). We also have to make a messenger instance accessible through `MXRAndroidSystem.Messenger` so we can send some undocumented/non-public messages to admin app. In short, we're adding new things to our public API but it had some issues:

- The [AndroidJavaObject API](https://docs.unity3d.com/ScriptReference/AndroidJavaObject.html) provides methods that can cause problems if invoked, such as `Dispose()`. It also have methods to get what looks like memory addresses of the object and class. Useful stuff when needed, but not in our case and it might encourage "clever" and unexpected usage via `messenger.Native` access

- We've used the term `Message` across the admin app and  the SDK, so it is part of our technical language. The `AndroidAppMessengerManager.cs` API provides an event that uses the term, but the messenger was also used to send Messages via `messenger.Native.Call("sendMessage", int, string)` which to an outsider would look like undocumented feature. The API should have methods such as `messenger.SendMessageToAdminApp(int, string)` that reflect the effect they have.

- Most usage doesn't need going a level below `IMXRSystem` API. But even if required, I feel that AdminAppMessengerManager, the C# version, should be a boundary for the SDK user and thus not have things in the API that requires knowledge of the Java side. By making the `AndroidJavaObject` object public we would be keeping that boundary open.

> Also `AndroidJavaObject.Call` can invoke private methods too. It might a good idea to just use `SendMessageToAdminApp` with the message type integer and thus not provide an indirect `AndroidJavaObject.Call` method in any way at all, which we are currently doing via `AdminAppMessengerManager.Call` that allow us to send undocumented/non-public messages. Doing this would mean the messenger can only do 3 things 1) tell if it's bound, 2) raise an event when a message is received, 3) send a message to the admin app if it is bound. This looks like a might tighter API to me as everything the messenger can do is message related.

2023-03-20 19:53 UTC, johnmanagexr commented
Cool, thanks for the clear explanation here! I think these are all great points. It would be ideal if they were included in the TDD / as comments in the code for additional clarity. 

That being said, LGTM.

2023-03-20 19:54 UTC, johnmanagexr approved these changes

2023-03-20 21:00 UTC, merged