Ignore case when checking manufacturer for Pico vs PICO.
ManageXR/mxr-unity-sdk pull request #49
Opened 2023-08-16 09:26 UTC by lukefwilson

Do the same for other models and manufacturers for future proofing

2023-08-16 18:54 UTC, Aleyum approved these changes

2023-08-16 20:57 UTC, Aleyum reviewed
Was this tested locally in Unity?

2023-08-16 23:59 UTC, johnmanagexr commented
> @lukefwilson Was this tested locally in Unity?

This was not tested locally! We need to test this locally / with a build on G3. Thanks Conor!

2023-08-17 20:17 UTC, johnmanagexr requested changes
@Aleyum  me know when we've tested this, then I'll remove my request changes and we can get this in!

2023-08-24 00:59 UTC, johnmanagexr approved these changes

2023-08-24 17:19 UTC, merged