Added isExpired field
ManageXR/mxr-unity-sdk pull request #53
Opened 2023-09-14 17:02 UTC by Aleyum

- Added isExpired field to  `ContentTypes`

2023-09-14 23:43 UTC, johnmanagexr requested changes

2023-09-14 23:43 UTC, johnmanagexr commented on Assets/MXR.SDK/Runtime/Types/ContentTypes.cs
> +        /// Whether the application has expired or not
This comment mostly just reiterates the name of the field. Can you make this clear to someone with less context who is looking at our SDK?

Maybe something like: 

"Whether the application is currently in an expired state, which happens on shared applications when they reach the end of their shared time limit."

2023-09-15 00:22 UTC, johnmanagexr approved these changes

2023-09-19 17:57 UTC, adrenak approved these changes

2023-10-11 19:41 UTC, adrenak commented
Raised some new points for a couple of util methods

2023-10-13 19:04 UTC, adrenak requested changes

2023-10-20 01:23 UTC, johnmanagexr commented on Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
> +        public static string EnumToString<TEnum>(TEnum enumValue) where TEnum : Enum {
This is resolved without a comment - is there a reason for this?

If you chatted about this offline, it's worthwhile to follow up on a comment here as well!

2023-10-20 01:26 UTC, johnmanagexr commented on Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
> +        public static string MillisecondsToDate(long dateInMS) {
Same here

2023-10-20 01:27 UTC, johnmanagexr requested changes
Just following up on loose ends, otherwise looks good

2023-10-20 17:42 UTC, Aleyum commented on Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
> +        public static string EnumToString<TEnum>(TEnum enumValue) where TEnum : Enum {
Resolved via DMs, just forgot to remove the unused method.

2023-10-20 17:54 UTC, Aleyum commented on Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
> +        public static string MillisecondsToDate(long dateInMS) {
Again, moved this but forgot to remove the original function

2023-10-25 13:18 UTC, adrenak approved these changes

2023-10-25 18:56 UTC, johnmanagexr approved these changes

2023-10-25 20:06 UTC, merged